# Generated by Django 6.0.7 on 2026-08-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
